<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select One--DIII Teknik ListrikDI_0fcfc2</name>
   <tag></tag>
   <elementGuidId>19b69148-51cd-4ba4-8bf3-76861f563dbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prodiId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='prodiId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prodiId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prodiId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select One--DIII Teknik ListrikDIII Teknik ElektronikaDIII Teknik TelekomumnikasiDIV Teknik ElektronikaDIV Teknik TelekomunikasiDIV Teknik Otomasi IndustriDIII Teknik AeronautikaDIII Teknik MesinDIII Teknologi MesinDIV Proses ManufakturDIV Teknik Perancangan dan Konstruksi MesinDIII Konstruksi SipilDIII Konsentrasi GedungDIV Teknik Perancangan Jalan dan JembatanDIV Teknik Perawatan dan Perbaikan GedungDIII Teknik konversi EnergiDIV Teknik Konversi EnergiDIV Teknologi Pembangkit Tenaga ListrikDIII Teknik Refrigerasi dan Tata UdaraDIV Teknik Refrigerasi dan Tata UdaraDIII Teknik InformatikaDIV Teknik InformatikaDIII Teknik KimiaDIII Analis KimiaDIV Teknik Kimia Produksi BersihDIII AkuntansiDIII Keuangan PerbankanDIV AkuntansiDIV Akuntansi Manajemen PemerintahanDIV Keuangan SyariahDIII Administrasi BisnisDIII Manajemen PemasaranDIII Administrasi BisnisDIV Administrasi BisnisDIV Manajemen PemasaranDIV Manajemen Aset</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prodiId&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='prodiId']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formMember']/div[3]/div[2]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBMIT'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[2]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'prodiId' and @name = 'prodiId' and (text() = '-- Select One--DIII Teknik ListrikDIII Teknik ElektronikaDIII Teknik TelekomumnikasiDIV Teknik ElektronikaDIV Teknik TelekomunikasiDIV Teknik Otomasi IndustriDIII Teknik AeronautikaDIII Teknik MesinDIII Teknologi MesinDIV Proses ManufakturDIV Teknik Perancangan dan Konstruksi MesinDIII Konstruksi SipilDIII Konsentrasi GedungDIV Teknik Perancangan Jalan dan JembatanDIV Teknik Perawatan dan Perbaikan GedungDIII Teknik konversi EnergiDIV Teknik Konversi EnergiDIV Teknologi Pembangkit Tenaga ListrikDIII Teknik Refrigerasi dan Tata UdaraDIV Teknik Refrigerasi dan Tata UdaraDIII Teknik InformatikaDIV Teknik InformatikaDIII Teknik KimiaDIII Analis KimiaDIV Teknik Kimia Produksi BersihDIII AkuntansiDIII Keuangan PerbankanDIV AkuntansiDIV Akuntansi Manajemen PemerintahanDIV Keuangan SyariahDIII Administrasi BisnisDIII Manajemen PemasaranDIII Administrasi BisnisDIV Administrasi BisnisDIV Manajemen PemasaranDIV Manajemen Aset' or . = '-- Select One--DIII Teknik ListrikDIII Teknik ElektronikaDIII Teknik TelekomumnikasiDIV Teknik ElektronikaDIV Teknik TelekomunikasiDIV Teknik Otomasi IndustriDIII Teknik AeronautikaDIII Teknik MesinDIII Teknologi MesinDIV Proses ManufakturDIV Teknik Perancangan dan Konstruksi MesinDIII Konstruksi SipilDIII Konsentrasi GedungDIV Teknik Perancangan Jalan dan JembatanDIV Teknik Perawatan dan Perbaikan GedungDIII Teknik konversi EnergiDIV Teknik Konversi EnergiDIV Teknologi Pembangkit Tenaga ListrikDIII Teknik Refrigerasi dan Tata UdaraDIV Teknik Refrigerasi dan Tata UdaraDIII Teknik InformatikaDIV Teknik InformatikaDIII Teknik KimiaDIII Analis KimiaDIV Teknik Kimia Produksi BersihDIII AkuntansiDIII Keuangan PerbankanDIV AkuntansiDIV Akuntansi Manajemen PemerintahanDIV Keuangan SyariahDIII Administrasi BisnisDIII Manajemen PemasaranDIII Administrasi BisnisDIV Administrasi BisnisDIV Manajemen PemasaranDIV Manajemen Aset')]</value>
   </webElementXpaths>
</WebElementEntity>
